# Generated by Django 5.0.5 on 2024-05-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registrationapp.eventsection'),
            preserve_default=False,
        ),
    ]
