# Generated by Django 5.0.5 on 2024-05-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_registration_event_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registrationapp.eventsection'),
        ),
    ]
