# Generated by Django 5.0.5 on 2024-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0004_dietsection_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietsection',
            name='diet_description',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Gluten-Free', 'Gluten-Free'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Shellfish-Free', 'Shellfish-Free'), ('Soy-Free', 'Soy-Free'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
