# Generated by Django 5.0.5 on 2024-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0005_alter_dietsection_diet_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventSection',
            new_name='EventSession',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='event_section',
            new_name='event_session',
        ),
        migrations.AlterField(
            model_name='dietsection',
            name='diet_description',
            field=models.CharField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Gluten-Free', 'Gluten-Free'), ('Dairy-Free', 'Dairy-Free'), ('Nut-Free', 'Nut-Free'), ('Shellfish-Free', 'Shellfish-Free'), ('Soy-Free', 'Soy-Free')], default='None', max_length=50),
        ),
    ]
