# Generated by Django 5.0.5 on 2024-05-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0006_rename_eventsection_eventsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.eventsession'),
        ),
    ]
